### ISSUE TITLE
“org.gnome.FontManager” is unable to be invoked via gnome-shell.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [flathub/org.gnome.FontManager#13]
`flatpak run org.gnome.FontManager` invokes it, as does invocation via `gnome-software`. However, `gnome-shell` is apparently unable to.

**Comment by Eonfge** [comment]
Can you give me your console output? 

This is mine:
```
[kevin@kevin-at-fedora ~]$ flatpak run -v org.gnome.FontManager 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/kevin/.local/share/flatpak
F: Opening user flatpak installation at path /home/kevin/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/kevin/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Regenerating ld.so.cache /home/kevin/.var/app/org.gnome.FontManager/.ld.so/d0dd827b6f4b6ef6f311717039ac6ed4fdf5af621ebddda2ef27bbe04ed2fc2a
F: Running: 'bwrap --args 23 ldconfig -X -C /run/ld-so-cache-dir/d0dd827b6f4b6ef6f311717039ac6ed4fdf5af621ebddda2ef27bbe04ed2fc2a.mLyNBh'
F: Allocated instance id 515717337
F: Add defaults in dir /org/gnome/FontManager/
F: Add locks in dir /org/gnome/FontManager/
F: Allowing wayland access
F: Allowing x11 access
F: Running 'bwrap --args 40 xdg-dbus-proxy --args=42'
F: Running 'bwrap --args 40 font-manager'
Gtk-Message: 19:31:25.423: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:31:25.423: Failed to load module "pk-gtk-module"
Gtk-Message: 19:31:25.424: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:31:25.424: Failed to load module "pk-gtk-module"
[font-manager]-Message: 19:31:25.461: ArchiveManager.vala:59: Install file-roller to enable archive support
```

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/org.gnome.FontManager/issues/13#issuecomment-921964764

After an update by `rpm-ostree`, I am now able to. Therefore, I shall close this issue.
I certainly should have posted my logs. I am storing them, but because I am doubtful that this problem is affecting anybody else, I shall not post them.

**Comment by roke-julian-lockhart** [comment]
<details>

"http://github.com/flathub/org.gnome.FontManager/issues/13#issuecomment-922272696" responds to "http://github.com/flathub/org.gnome.FontManager/issues/13#issuecomment-921964764".

</details>

@Eonfge, after an update by `rpm-ostree`, I have become able to. Consequently, I shall close this issue. I certainly should have posted my logs. I am storing them, but because I doubt that this problem is affecting anybody else, I shall not bother to post them.
