### ISSUE TITLE
runtime org.gnome.Platform branch 42 is end-of-life

### ISSUE THREAD

**Issue by superuser-miguel** [flathub/org.gnome.FontManager#17]
The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.

**Comment by Eonfge** [comment]
Got it, this one got on the backburner for a bit, but I'm looking into it now.

**Comment by Eonfge** [comment]
Well, more complex then initially expected. Got an issue I have to discuss with upstream:
https://github.com/FontManager/font-manager/issues/317

**Comment by Eonfge** [comment]
Got this addressed for now... Sadly, seems that the application doesn't work at all
