### ISSUE TITLE
Application doesn't work, because it can't access home config

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.FontManager#28]
We previously had a workaround that allowed us to change home-level fonts, while working from within Flatpak. Sadly, this workaround no longer works on the latest versions of Flatpak. 

```
  # XDG Data/Fonts location
  - --filesystem=xdg-data/fonts
  - --persist=xdg-data/fonts

  # XDG complient locations for font config
  - --filesystem=xdg-config/fontconfig
  - --persist=xdg-config/fontconfig
```

There is not really something that we can do, without the help from Upstream. The irony is that the application should ignore `xdg-` parameters and should instead write to `~/.config/fontconfig/conf.d/` and `~/.local/share/fonts` instead.

**Comment by Eonfge** [comment]
@JerryCasiano Not sure what to do know. Not sure if I can get this application working again without your help. This is one example where the sandboxing of Flathub should be ignored, since we explicitly  want to change fonts on a user-level.

**Comment by JerryCasiano** [comment]
Sorry, don't have access to an actual computer right now. Will be back over the weekend and can have a look then.

Just to make sure I'm understanding correctly though 

We now need what amounts to hard coded paths to make it work?

Because that shouldn't be much of a problem but just seems all kinds of wrong ..

**Comment by Eonfge** [comment]
> Because that shouldn't be much of a problem but just seems all kinds of wrong

I too am not sure, it just behaves quite weird. Perhaps we should do some extra tests

**Comment by JerryCasiano** [comment]
So I tried reproducing this and couldn't...

I'm on Fedora 39. It worked as expected. I didn't test extensively though, just loaded it and disabled a font. 

What OS is it failing on?

**Comment by Eonfge** [comment]
Think that this is fixed now, but I had trouble testing it myself so I'll look into that
